/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.AccountBLL;
import BLL.CustomerBLL;
import javax.swing.table.DefaultTableModel;
import BLL.StaffBLL;
import DTO.AccountDTO;
import DTO.CustomerDTO;
import DTO.StaffDTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class ManagerMainForm extends javax.swing.JFrame {
    DefaultTableModel staffTableModel;
    DefaultTableModel accountTableModel;
    DefaultTableModel customerTableModel;
    
    StaffBLL staffBLL;
    AccountBLL accountBLL;
    CustomerBLL customerBLL;
    
    AccountDTO account;
    /**
     * Creates new form ManagerMainForm
     */
    public ManagerMainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        staffBLL = new StaffBLL();
        staffTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }   
        };
        //Table Staff
        staffTable.setModel(staffTableModel);
        staffTableModel.addColumn("Staff ID");
        staffTableModel.addColumn("Name");
        staffTableModel.addColumn("Salary");
        staffTableModel.addColumn("Work years");
        staffTableModel.addColumn("Job");
        setTableDataStaff(staffBLL.getAllStaff());
        
        //Table Account
        accountBLL = new AccountBLL();
        accountTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        accountTable.setModel(accountTableModel);
        accountTableModel.addColumn("Account ID");
        accountTableModel.addColumn("username");
        accountTableModel.addColumn("password");
        accountTableModel.addColumn("role");
        accountTableModel.addColumn("staff ID");
        setTableDataAccount(accountBLL.getAllAccount());
        
        //Table Customer
        customerBLL = new CustomerBLL();
        customerTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        customerTabel.setModel(customerTableModel);
        customerTableModel.addColumn("Customer ID");
        customerTableModel.addColumn("First Name");
        customerTableModel.addColumn("Last Name");
        customerTableModel.addColumn("Phone");
        
        setTableDataCustomer(customerBLL.getAllCustomer());
    }
    private void setTableDataStaff( ArrayList<StaffDTO> staffList){
        for (StaffDTO staff : staffList){
            staffTableModel.addRow(new Object[]{
                staff.getStaffID(),
                staff.getStaffName(),
                staff.getSalary(),
                staff.getWorkYears(),
                staff.getJob()
            });
        }
    }
    
    private void setTableDataAccount( ArrayList<AccountDTO> accountList){
        for (AccountDTO account : accountList){
            accountTableModel.addRow(new Object[]{
                account.getAccountID(),
                account.getUsername(),
                account.getPassword(),
                account.getRole(),
                account.getStaffID()
            });
        }
    }
    
    private void setTableDataCustomer( ArrayList<CustomerDTO> customerList){
        for (CustomerDTO customer : customerList){
            customerTableModel.addRow(new Object[]{
                customer.getCustomerID(),
                customer.getFirstName(),
                customer.getLastName(),
                customer.getPhone()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managerTablePane = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTabel = new javax.swing.JTable();
        refreshCustomerButton = new javax.swing.JButton();
        addCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        updateCustomerButton = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        addAccountButton = new javax.swing.JButton();
        refreshAccountButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();
        updateAccountButton = new javax.swing.JButton();
        staffPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        addStaff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");

        managerTablePane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        customerTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(customerTabel);

        refreshCustomerButton.setText("Tải lại");
        refreshCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerButton.setText("Thêm mới");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setText("Xóa");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        updateCustomerButton.setText("Sửa");
        updateCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(addCustomerButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateCustomerButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshCustomerButton)
                        .addContainerGap())))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshCustomerButton)
                    .addComponent(addCustomerButton)
                    .addComponent(deleteCustomerButton)
                    .addComponent(updateCustomerButton))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        managerTablePane.addTab("Khách hàng", customerPanel);

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(accountTable);

        addAccountButton.setText("Thêm mới");
        addAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountButtonActionPerformed(evt);
            }
        });

        refreshAccountButton.setText("Tải lại");
        refreshAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAccountButtonActionPerformed(evt);
            }
        });

        deleteAccountButton.setText("Xóa");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        updateAccountButton.setText("Sửa");
        updateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(addAccountButton)
                        .addGap(13, 13, 13)
                        .addComponent(updateAccountButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAccountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshAccountButton)
                        .addGap(22, 22, 22))))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAccountButton)
                    .addComponent(refreshAccountButton)
                    .addComponent(deleteAccountButton)
                    .addComponent(updateAccountButton))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        managerTablePane.addTab("Tài khoản", accountPanel);

        refreshButton.setBackground(new java.awt.Color(204, 204, 204));
        refreshButton.setText("Tải lại");
        refreshButton.setPreferredSize(new java.awt.Dimension(83, 23));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 51, 51));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(51, 255, 51));
        updateButton.setText("Sửa");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        addStaff.setText("Thêm mới");
        addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffActionPerformed(evt);
            }
        });

        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        staffTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        staffTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        staffTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(staffTable);

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addComponent(addStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaff)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        managerTablePane.addTab("Nhân viên", staffPanel);

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 51, 153));
        TitleLabel.setText("Quản lý nhà hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(TitleLabel)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTablePane)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managerTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffActionPerformed
        // TODO add your handling code here:
        new addAccountForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStaffActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int row = staffTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this,"Vui long chon nhan vien", "loi", JOptionPane.ERROR_MESSAGE);
        } else{
            int staffID = Integer.parseInt(String.valueOf(staffTable.getValueAt(row, 0)));

            new updateStaffFrame(staffID).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = staffTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this, "Vui long chon staff truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(ManagerMainForm.this, "Ban co chac chan muon xoa khong?");
            if(confirm==JOptionPane.YES_OPTION){
                int staffID = Integer.parseInt(String.valueOf(staffTable.getValueAt(row, 0)));
                accountBLL.deleteAccountByStaffID(staffID);
                staffBLL.deleteStaff(staffID);
                
                staffTableModel.setRowCount(0);
                setTableDataStaff(staffBLL.getAllStaff());
                
                accountTableModel.setRowCount(0);
                setTableDataAccount(accountBLL.getAllAccount());
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        staffTableModel.setRowCount(0);
        setTableDataStaff(staffBLL.getAllStaff());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        // TODO add your handling code here:
        int row = accountTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this, "Vui long chon truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(ManagerMainForm.this, "Ban co chac chan muon xoa khong?");
            if(confirm==JOptionPane.YES_OPTION){
                int accountID = Integer.parseInt(String.valueOf(accountTable.getValueAt(row, 0)));
                account = accountBLL.getAccountByID(accountID);
                int staffID = account.getStaffID();
                accountBLL.deleteAccount(accountID);
                staffBLL.deleteStaff(staffID);

                accountTableModel.setRowCount(0);
                setTableDataAccount(accountBLL.getAllAccount());
                
                staffTableModel.setRowCount(0);
                setTableDataStaff(staffBLL.getAllStaff());
            }
        }
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void refreshAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAccountButtonActionPerformed
        // TODO add your handling code here:
        accountTableModel.setRowCount(0);
        setTableDataAccount(accountBLL.getAllAccount());
    }//GEN-LAST:event_refreshAccountButtonActionPerformed

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed
        // TODO add your handling code here:
        new addAccountForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAccountButtonActionPerformed

    private void updateCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerButtonActionPerformed
        // TODO add your handling code here:
        int row = customerTabel.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this,"Vui long chon", "loi", JOptionPane.ERROR_MESSAGE);
        } else{
            int customerID = Integer.parseInt(String.valueOf(customerTabel.getValueAt(row, 0)));

            new updateCustomerForm(customerID).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateCustomerButtonActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        // TODO add your handling code here:
        int row = customerTabel.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this, "Vui long chon truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(ManagerMainForm.this, "Ban co chac chan muon xoa khong?");
            if(confirm==JOptionPane.YES_OPTION){
                int customerID = Integer.parseInt(String.valueOf(customerTabel.getValueAt(row, 0)));
                customerBLL.deleteCustomer(customerID);

                customerTableModel.setRowCount(0);
                setTableDataCustomer(customerBLL.getAllCustomer());
            }
        }
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        new addCustomerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void refreshCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCustomerButtonActionPerformed
        // TODO add your handling code here:
        customerTableModel.setRowCount(0);
        setTableDataCustomer(customerBLL.getAllCustomer());
    }//GEN-LAST:event_refreshCustomerButtonActionPerformed

    private void updateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountButtonActionPerformed
        // TODO add your handling code here:
        int row = accountTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ManagerMainForm.this,"Vui long chon tai khoan", "loi", JOptionPane.ERROR_MESSAGE);
        } else{
            int accountID = Integer.parseInt(String.valueOf(accountTable.getValueAt(row, 0)));

            new updateAccountFrame(accountID).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JTable accountTable;
    private javax.swing.JButton addAccountButton;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addStaff;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTabel;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane managerTablePane;
    private javax.swing.JButton refreshAccountButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshCustomerButton;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JTable staffTable;
    private javax.swing.JButton updateAccountButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateCustomerButton;
    // End of variables declaration//GEN-END:variables
}
