/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.CustomerBLL;
import DTO.CustomerDTO;

/**
 *
 * @author PC
 */
public class updateCustomerForm extends javax.swing.JFrame {
    CustomerBLL customerBLL;
    CustomerDTO customer;
    /**
     * Creates new form updateCustomerForm
     */
    public updateCustomerForm(int customerID) {
        customer = new CustomerDTO();
        customerBLL = new CustomerBLL();
        customer = customerBLL.getCustomerById(customerID);
        
        initComponents();
        
        idCustomerTextflied.setText(String.valueOf(customer.getCustomerID()));
        FirstnameTextfield.setText(customer.getFirstName());
        LastNameTextField.setText(customer.getLastName());
        PhoneTextField.setText(customer.getPhone());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tilteLabel = new javax.swing.JLabel();
        idCustomerTextflied = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        FirstnameTextfield = new javax.swing.JTextField();
        salaryLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        workyearsLabel = new javax.swing.JLabel();
        PhoneTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Trở lại");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ID nhân viên");

        tilteLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tilteLabel.setText("Cập nhật khách hàng");

        idCustomerTextflied.setEditable(false);
        idCustomerTextflied.setEnabled(false);
        idCustomerTextflied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCustomerTextfliedActionPerformed(evt);
            }
        });

        nameLabel.setText("Họ");

        FirstnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextfieldActionPerformed(evt);
            }
        });

        salaryLabel.setText("Tên");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        workyearsLabel.setText("Số điện thoại");

        updateButton.setText("Xác nhận");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(tilteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workyearsLabel)
                            .addComponent(salaryLabel)
                            .addComponent(nameLabel))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FirstnameTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(LastNameTextField)
                            .addComponent(PhoneTextField)
                            .addComponent(idCustomerTextflied)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(updateButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tilteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idCustomerTextflied, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(FirstnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workyearsLabel)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(updateButton)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new ManagerMainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void FirstnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextfieldActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        customer.setCustomerID(Integer.parseInt(idCustomerTextflied.getText()));
        customer.setFirstName(FirstnameTextfield.getText());
        customer.setLastName(LastNameTextField.getText());
        customer.setPhone(PhoneTextField.getText());
        

        customerBLL.updateCustomer(customer);

        new ManagerMainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void idCustomerTextfliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCustomerTextfliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCustomerTextfliedActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstnameTextfield;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField idCustomerTextflied;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel tilteLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel workyearsLabel;
    // End of variables declaration//GEN-END:variables
}
